"""Lifecycle values shared by runtime storage and public contracts."""

from enum import StrEnum


class RunStatus(StrEnum):
    QUEUED = "RUN_STATUS_QUEUED"
    RUNNING = "RUN_STATUS_RUNNING"
    WAITING = "RUN_STATUS_WAITING"
    COMPLETED = "RUN_STATUS_COMPLETED"
    FAILED = "RUN_STATUS_FAILED"
    CANCELLED = "RUN_STATUS_CANCELLED"


class JobStatus(StrEnum):
    QUEUED = "JOB_STATUS_QUEUED"
    RUNNING = "JOB_STATUS_RUNNING"
    WAITING = "JOB_STATUS_WAITING"
    SUCCEEDED = "JOB_STATUS_SUCCEEDED"
    FAILED = "JOB_STATUS_FAILED"
    CANCELLED = "JOB_STATUS_CANCELLED"


class TaskStatus(StrEnum):
    READY = "TASK_STATUS_READY"
    RUNNING = "TASK_STATUS_RUNNING"
    WAITING = "TASK_STATUS_WAITING"
    SUCCEEDED = "TASK_STATUS_SUCCEEDED"
    FAILED = "TASK_STATUS_FAILED"
    CANCELLED = "TASK_STATUS_CANCELLED"


class InferenceStatus(StrEnum):
    PREPARED = "INFERENCE_STATUS_PREPARED"
    IN_FLIGHT = "INFERENCE_STATUS_IN_FLIGHT"
    SUCCEEDED = "INFERENCE_STATUS_SUCCEEDED"
    FAILED = "INFERENCE_STATUS_FAILED"
    UNKNOWN = "INFERENCE_STATUS_UNKNOWN"


class InferencePurpose(StrEnum):
    MAIN = "INFERENCE_REQUEST_PURPOSE_MAIN"
    CLASSIFIER = "INFERENCE_REQUEST_PURPOSE_CLASSIFIER"
    TITLE = "INFERENCE_REQUEST_PURPOSE_TITLE"
